### PR TITLE
Fix #471: obfuscate authorization header values in errors

### LINKED ISSUE #471: Don't include authorization information in exceptions
@rfk points out in https://bugzilla.mozilla.org/show_bug.cgi?id=1566529 that log messages including credentials is probably bad.

### PR DESCRIPTION
**Pull request by leplatrem**
Fix #471

There were many ways to solve this... I could have obfuscated the value in the error constructor, could have removed the options from the logging message, etc. 
Let me know what do you think!

### CODE REVIEW

File: test/http_test.js [hunk 1]
```diff
@@ -130,14 +130,31 @@ describe("HTTP class", () => {
...
+        return http
+          .request("/", {
+            mode: "cors",
+            headers: {
+              Authorization: "XXX",
+              "User-agent": "mocha-test",
+            },
+          })
+          .should.be.rejectedWith(
+            'Timeout while trying to access / with {"mode":"cors","headers":{"Accept":"application/json","Content-Type":"application/json","Authorization":"XXX","User-agent":"mocha-test"}}'
```
Comment (glasserc) [inline test/http_test.js]: We have this test that shows that the Authorization header is shown, but we don't have a test showing that the Authorization header is actually redacted?
