### PR TITLE
Fix #963: Fix snapshot when records were deleted via plural endpoint

### LINKED ISSUE #963: Snapshot of collection is incorrect if records deleted via the plural endpoint
Because of https://github.com/Kinto/kinto/issues/1649, the records that are deleted via the plural endpoint are not correctly handled in the snapshot.

**Steps to reproduce**

```js
await coll.createRecord({ n: 1 });
await coll.createRecord({ n: 2 });
await coll.createRecord({ n: 2 });
await coll.deleteRecords({
  filters: {
    eq_n: 2,
  }
});
const { data: rec3 } = await coll.createRecord({ n: 3 });
const { data } = await coll.listRecords({
  at: rec3.last_modified,
});
```

**Expected**

```js
[{ n: 3 }, { n: 1 }]
```

**Actual**

`[{ n: 3 }, { n: 2 }, { n: 2 }, { n: 1 }]`

### PR DESCRIPTION
**Pull request by leplatrem**
Unfortunately the fix in #956 was not enough to cover the misbehavior of the Admin UI diff view. I traced it back and it was related to the fact that plural deletes do not generate history entries.

This approach seems to work as expected, and does not introduce too much performance loss

Fixes #963

### CODE REVIEW

File: src/collection.ts [hunk 1]
```diff
@@ -768,7 +767,14 @@ export default class Collection {
   /**
    * @private
    */
-  async listChangesUntil<T>(at: number): Promise<HistoryEntry<T>[]> {
+  @capable(["history"])
```
Comment (Natim) [inline src/collection.ts:770]: What is this syntax?

Comment (leplatrem) [reply src/collection.ts:770]: https://docs.google.com/document/d/1ikxIP5-RVYq6d_f8lAvf3pKC00W78ueyp-xIZ6q67uU/edit
